# -*- python -*-
import os.path as op
Import('env')

srcs = env.Glob('*.py')
srcs.remove(env.File('b_plus_tree.py'))
srcs.remove(env.File('skiplist_lib.py'))
pdfs = [env.fathom(x, PYTHONPATH='#fathom/src/') for x in srcs]
env.Depends(env.File('b_plus_tree_origin.pdf'), env.File('b_plus_tree.py'))
env.Depends(env.File('b_plus_tree_insert3.pdf'), env.File('b_plus_tree.py'))
env.Depends(env.File('skiplist.pdf'), env.File('skiplist_lib.py'))
env.Depends(env.File('skiplist_seek.pdf'), env.File('skiplist_lib.py'))
env.Depends(env.File('trie.pdf'), env.File('skiplist_lib.py'))
env.Depends(env.File('bkd.pdf'), env.File('skiplist_lib.py'))
